#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build
bundle exec htmlproofer ./_site --assume-extension --check-html --http-status-ignore 429 --only-4xxn--typhoeus-config '{"connecttimeout":"60", "timeout":"60"}' 
